apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 8090
    targetPort: http
    name: http
  selector:
    app: nginx-{{ .Release.Name }}
